Dashboard/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Connection;
using Repository;
using Domain.Manage;
using Domain.Interfaces;
using Domain.Models.Articulo;
using Dashboard.Security;
using Domain.Models.AlmacenProducto;

namespace Dashboard.Controllers
{
    public class ArticleController : Controller
    {
        private IGenericRepository<Articulos> _gArticle;
        private IGenericRepository<TipoProducto> _gArticleType;
        private IGenericRepository<Iva> _gIVA;
        private IGenericRepository<Estados> _gStatus;
        private IGenericRepository<Almacenes> _gStore;

        #region Constructors

        public ArticleController(IGenericRepository<Articulos> gArticle,
                                 IGenericRepository<TipoProducto> gArticleType,
                                 IGenericRepository<Iva> gIVA,
                                 IGenericRepository<Estados> gStatus,
                                 IGenericRepository<Almacenes> gStore)
        {
            this._gArticle = gArticle;
            this._gArticleType = gArticleType;
            this._gIVA = gIVA;
            this._gStatus = gStatus;
            this._gStore = gStore;
        }
        #endregion


        public ActionResult Index()
        {
            var elements = _gArticle.GetAll().ToList();
            var modelList = AutoMapper.Mapper.Map<IEnumerable<Articulos>, IEnumerable<mArticle>>(elements);

            return View(modelList);
        }

        
        [HttpGet]
        public ActionResult Create()
        {
            var model = new mArticleCreate();
            model.listaEstados = new SelectList(_gStatus.GetAll().ToList(), "Id", "Nombre");
            model.listIva = new SelectList(_gIVA.GetAll().ToList(), "Id", "Valor");
            model.listaTipos = new SelectList(_gArticleType.GetAll().ToList(), "Id", "Nombre");


            //ViewBag.Estado = new SelectList(_gStatus.GetAll().ToList(), "Id", "Nombre");
            //ViewBag.Tipo = new SelectList(_gArticleType.GetAll().ToList(), "Id", "Nombre");
            //ViewBag.IVA = new SelectList(_gIVA.GetAll().ToList(), "Id", "Valor");

            return View(model);
        }



        [HttpPost]
        public ActionResult Create(Articulos element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = AutoMapper.Mapper.Map<Articulos, mArticleCreate>(element);
                    model.listaEstados = new SelectList(_gStatus.GetAll().ToList(), "Id", "Nombre");
                    model.listIva = new SelectList(_gIVA.GetAll().ToList(), "Id", "Valor");
                    model.listaTipos = new SelectList(_gArticleType.GetAll().ToList(), "Id", "Nombre");

                    return View(model);
                }

                _gArticle.Add(element);
                _gArticle.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el cliente. " + ex);
            }

            return RedirectToAction("Index");

        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            var element = _gArticle.FindBy(x => x.IdArticulo == id).FirstOrDefault();
            var model = AutoMapper.Mapper.Map<Articulos, mArticleCreate>(element);

            model.listaEstados = new SelectList(_gStatus.GetAll().ToList(), "Id", "Nombre");
            model.listIva = new SelectList(_gIVA.GetAll().ToList(), "Id", "Valor");
            model.listaTipos = new SelectList(_gArticleType.GetAll().ToList(), "Id", "Nombre");

            return View(model);
        }





        [HttpPost]
        public ActionResult Edit(Articulos element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = AutoMapper.Mapper.Map<Articulos, mArticleCreate>(element);
                    model.listaEstados = new SelectList(_gStatus.GetAll().ToList(), "Id", "Nombre");
                    model.listIva = new SelectList(_gIVA.GetAll().ToList(), "Id", "Valor");
                    model.listaTipos = new SelectList(_gArticleType.GetAll().ToList(), "Id", "Nombre");
                    return View(model);
                }

                _gArticle.Edit(element);
                _gArticle.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el articulo." + ex);
            }

            return RedirectToAction("Index");
        }



        public ActionResult _Details(int id)
        {
            var idStore = User.ToCustomPrincipal().CustomIdentity.ActiveStore;
            var e = _gStore.FindBy(x => x.Id == idStore).FirstOrDefault();
            var element = e.Almacen_Productos.Where(x => x.Id == id).FirstOrDefault();
            var model = AutoMapper.Mapper.Map<Almacen_Productos, mAlmacenProducto>(element);

            return PartialView(model);
        }



        public ActionResult DeleteConfirmed(int id)
        {
            var element = _gArticle.FindBy(x => x.IdArticulo == id).FirstOrDefault();
            var model = AutoMapper.Mapper.Map<Articulos, mArticle>(element);

            return View(model);
        }



        [HttpPost]
        public ActionResult Delete(Articulos element)
        {
            try
            {
                _gArticle.Delete(element);
                _gArticle.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar eliminar el articulo." + ex);
            }

            return RedirectToAction("Index");
        }
    }
}

Dashboard/Controllers/PedidoCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Models.PedidoC;
using Domain.Interfaces;
using Repository;
using AutoMapper;
using Domain.DefaultValues;
using Domain.Tools;

namespace Dashboard.Controllers
{
    public class PedidoCController : Controller
    {
        #region Parametros

        private IGenericRepository<Pedido_c> _gPedidoC;
        private IGenericRepository<Clientes> _gClient;
        private IGenericRepository<FormaPago> _gPaymentType;
        private IGenericRepository<EstadosPedido> _gOrderStatus;
        private IGenericRepository<Almacenes> _gStore;
        private IGenericRepository<Linea_pedido_c> _gOrderLine;

        #endregion


        #region Constructores

        public PedidoCController(IGenericRepository<Pedido_c> gPedidoC,
                                 IGenericRepository<EstadosPedido> gOrderStatus,
                                 IGenericRepository<FormaPago> gPaymentType,
                                 IGenericRepository<Clientes> gClient,
                                 IGenericRepository<Almacenes> gStore,
                                 IGenericRepository<Linea_pedido_c> gOrderLine)
        {
            this._gPedidoC = gPedidoC;
            this._gOrderStatus = gOrderStatus;
            this._gPaymentType = gPaymentType;
            this._gClient = gClient;
            this._gStore = gStore;
            this._gOrderLine = gOrderLine;
        }

        #endregion


        [HttpGet]
        public ActionResult Index()
        {
            var list = _gPedidoC.GetAll().ToList();
            var modelList = Mapper.Map<IEnumerable<Pedido_c>, IEnumerable<mPedidoC>>(list).ToList();

            return View(modelList);
        }



        [HttpGet]
        public ActionResult Create()
        {
            var model = new mPedidoCCreate();
            model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
            model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
            model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");
            
            return View(model);
        }



        [HttpPost]
        public ActionResult Create(Pedido_c element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
                    model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
                    model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
                    model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

                    return View(model);
                }

                _gPedidoC.Add(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el contacto. " + ex);
            }

            return RedirectToAction("Index");

        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();

            var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
            model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
            model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
            model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

            return View(model);
        }





        [HttpPost]
        public ActionResult Edit(Pedido_c element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
                    model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
                    model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
                    model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

                    return View(model);
                }

                _gPedidoC.Edit(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el contacto." + ex);
            }

            return RedirectToAction("Index");
        }





        public ActionResult DeleteConfirmed(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var model = AutoMapper.Mapper.Map<Pedido_c, mPedidoC>(element);

            return View(model);
        }



        [HttpPost]
        public ActionResult Delete(Pedido_c element)
        {
            try
            {
                _gPedidoC.Delete(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar eliminar el contacto." + ex);
            }

            return RedirectToAction("Index");
        }



        #region lineas pedido


        public ActionResult OpenOrder(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var model = Mapper.Map<Pedido_c, mPedidoC>(element);
            return View(model);
        }

        [HttpGet]
        public ActionResult OrderLineCreate(int id)
        {
            var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
            //ViewBag.idOrder = id;

            var model = new mOderLineCreate();
            model.Num_ped = id;


            var list = store.Almacen_Productos.Select(X =>
              new
              {
                  id = X.Id,
                  Name = X.Lote + " - " + X.Articulos.Nombre 
              }
            );

            model.ArticleList = new SelectList(list, "id", "Name");
            
            return PartialView(model);
        }


        [HttpPost]
        public ActionResult OrderLineCreate(Linea_pedido_c element)
        {
            var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
            var article = store.Almacen_Productos.Where(x => x.Id == element.idArticulo).FirstOrDefault();

            if(article.Stock >= element.Cantidad)
            {
                var order = _gPedidoC.FindBy(x => x.Num_ped == element.Num_ped).FirstOrDefault();
                article.Stock -= element.Cantidad;

                order.Peso += element.Cantidad * article.Articulos.Peso;
                order.Importe += (float) (element.Cantidad * article.Articulos.Precio);

                element.Total = (double)(element.Cantidad * article.Articulos.Precio);

                _gOrderLine.Add(element);

                _gOrderLine.Save();
                _gPedidoC.Save();
                _gStore.Save();

               
                TempData["MessageSucces"] = "Completado correctamente";
                TempData["Importe"] = order.Importe.ToString();
                TempData["Peso"] = (order.Peso/1000).ToString();

                var updateOrder = _gPedidoC.FindBy(x => x.Num_ped == element.Num_ped).FirstOrDefault();
                var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(updateOrder.Linea_pedido_c.ToList()).ToList();
                if (Request.IsAjaxRequest()) return PartialView("OrderLines", modelList);

            }else
            {
                TempData["MessageWarning"] = "No hay unidades suficientes";
            }

            return RedirectToAction("OpenOrder", new { id = element.Num_ped });
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult OrderLines(int id)
        {
            var order = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var list = order.Linea_pedido_c.ToList();

            var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(list).ToList();
          
            return PartialView(modelList);
        }


        [HttpPost]
        public ActionResult DeleteOrderLine(int idOrder , int idOrderLine)
        {
            try
            {
                var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
                var order = _gPedidoC.FindBy(x => x.Num_ped == idOrder).FirstOrDefault();
                var orderLine = order.Linea_pedido_c.Where(x => x.Linea == idOrderLine).FirstOrDefault();
                var article = store.Almacen_Productos.Where(x => x.Articulo == orderLine.Almacen_Productos.Articulos.IdArticulo).FirstOrDefault();

                order.Importe -= (float)(orderLine.Cantidad * orderLine.Almacen_Productos.Articulos.Precio);
                order.Peso -= (orderLine.Cantidad * orderLine.Almacen_Productos.Articulos.Peso);
                article.Stock += orderLine.Cantidad;
                
                order.Linea_pedido_c.Remove(orderLine);

                _gPedidoC.Save();
                _gStore.Save();

                TempData["MessageSucces"] = "Completado correctamente";
                TempData["Importe"] = order.Importe.ToString();
                TempData["Peso"] = (order.Peso / 1000).ToString();

                var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(order.Linea_pedido_c.ToList()).ToList();

                return PartialView("OrderLines",modelList);
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar eliminar una linea de pedido. " + ex);
            }

        }

Dashboard/Views/PedidoC/DeleteConfirmed.cshtml
@model Domain.Models.PedidoC.mPedidoC

<div class="row">
    <div class="col-xs-12">
        <div class="box box-danger flat">
            <div class="box-header with-border">
                <h3 class="box-title">¿Seguro que desea eliminar?</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div>
                    @Html.ValidationSummary(true, "", new { @class = "alert alert-danger alert-dismissable", style = "margin:20px;" })

                </div>

                <div class="col-xs-12">
                    @using (Html.BeginForm("Delete", "PedidoC", new { id = Model.Num_ped }, FormMethod.Post))
                    {
                        @Html.HiddenFor(model => model.Num_ped)
                        @Html.HiddenFor(model => model.idCliente)
                        @Html.HiddenFor(model => model.Estado)
                        @Html.HiddenFor(model => model.Forma_pago)
                        @Html.HiddenFor(model => model.Fecha_A)

                        <p>
                            <strong>@Html.DisplayNameFor(x => x.clienteNombre):</strong>
                            @Html.DisplayFor(x => x.clienteNombre)
                        </p>
                       
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.sForma_pago):</strong>
                            @Html.DisplayFor(x => x.sForma_pago)
                        </p>
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.sEstado):</strong>
                            @Html.DisplayFor(x => x.sEstado)
                        </p>
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.Fecha_A):</strong>
                            @Html.DisplayFor(x => x.Fecha_A)
                        </p>
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.Importe):</strong>
                            @Html.DisplayFor(x => x.Importe) €
                        </p>
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.Peso):</strong>
                            @Html.DisplayFor(x => x.Peso) .gr
                        </p>
                        <p>
                            <strong>@Html.DisplayNameFor(x => x.Observaciones):</strong>
                            @Html.DisplayFor(x => x.Observaciones)
                        </p>


                        <div>
                            <br />
                            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default flat" })
                            <input class="btn btn-danger flat" type="submit" value="Eliminar" />
                        </div>

                    }


                </div>

            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

Dashboard/Views/PedidoC/Index.cshtml
@model IEnumerable<Domain.Models.PedidoC.mPedidoC>


@{
    ViewBag.Title = "Pedidos cliente";
}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />

<div class="row">
    <div class="col-xs-12">
        <div class="box box-default flat">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewBag.Title</h3>
                @Html.ActionLink("Nuevo", "Create", "PedidoC", null, new { @class = "btn btn-primary pull-right flat" })
            </div><!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Num_ped)</th>
                            <th>@Html.DisplayNameFor(model => model.clienteNombre)</th>
                            <th>@Html.DisplayNameFor(model => model.sEstado)</th>
                            <th>@Html.DisplayNameFor(model => model.sForma_pago)</th>
                            <th>@Html.DisplayNameFor(model => model.Fecha_A)</th>
                            <th>@Html.DisplayNameFor(model => model.Peso) (kg.)</th>
                            <th>@Html.DisplayNameFor(model => model.Importe)</th>
                            <th>@Html.DisplayNameFor(model => model.Observaciones)</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(model => item.Num_ped)</td>
                                <td>@Html.DisplayFor(model => item.clienteNombre)</td>
                                <td>@Html.DisplayFor(model => item.sEstado)</td>
                                <td>@Html.DisplayFor(model => item.sForma_pago)</td>
                                <td>@Html.DisplayFor(model => item.Fecha_A)</td>
                                <td>@Html.DisplayFor(model => item.Peso) kg.</td>
                                <td>@Html.DisplayFor(model => item.Importe) €</td>
                                <td>@Html.DisplayFor(model => item.Observaciones)</td>
                                <td>
                                    @Html.ActionLink(" ", "Edit", "PedidoC", new { id = item.Num_ped }, new { @class = "btn btn-default btn-sm flat glyphicon glyphicon-pencil", title = "Editar" })
                                    <span> </span>
                                    @Html.ActionLink(" ", "OpenOrder", "PedidoC", new { id = item.Num_ped }, new { @class = "btn btn-default btn-sm flat glyphicon glyphicon-plus", title = "Añadir articulos" })
                                    <span> </span>
                                    @Html.ActionLink(" ", "DeleteConfirmed", "PedidoC", new { id = item.Num_ped }, new { @class = "btn btn-default btn-sm flat glyphicon glyphicon-trash", title = "Eliminar" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->
<!-- DATA TABES SCRIPT -->

<script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/1.0.7/js/dataTables.responsive.min.js" type="text/javascript"></script>
<!-- page script -->

<script type="text/javascript">
    $(function () {
        $('#example2').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json",
            }
        });
    });
</script>

Dashboard/Views/PedidoC/OrderLineCreate.cshtml
@model Domain.Models.PedidoC.mOderLineCreate

 @if (TempData["MessageWarning"] != null)
 {
    <script>
        $(".spValidation").show();
    </script>
 }

@if (TempData["MessageSucces"] != null)
{
    <script>
        $(".MyInput").val('');
        $(".lbl").text('');
    </script>
}


<div class="box box-primary flat">
    <div class="box-header with-border">
        <h3 class="box-title">Añadir detalle</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="form-horizontal">

            @using (Ajax.BeginForm("OrderLineCreate", "PedidoC",null,new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "Odrlist" }, new { id="_ajaxForm"}))
            {
                @Html.HiddenFor(x => x.Num_ped)

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.IdArticulo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IdArticulo, Model.ArticleList, "-- Selecciona --", new { @class = "form-control CformControl MyInput", id = "ArticleDrop" })
                            <small>@Html.ValidationMessageFor(model => model.IdArticulo, "", new { @class = "text-danger" })</small>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control CformControl MyInput" ,id="inputUd"} })
                            <small><span class="text-danger spValidation">No hay unidades suficientes</span></small>
                            <small>@Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default flat" })
                            <input type="button" onclick="ajaxSubmit()" value="Guardar" class="btn btn-primary flat" />
                        </div>
                    </div>
                </div>
            }

           
            <div class="col-md-6">
                <div class="well MyWell flat">
                    <h5 class="TitleHeader">Articulo</h5>
                    <div class="MyContent" id="ArtDetail">
                       @Html.Action("_Details","Article",new { id = 0})
                    </div>
                </div>
            </div>

        </div>
     

    </div><!-- /.box-body -->
</div><!-- /.box -->


<script type="text/javascript">

    $("#ArticleDrop").change(function () {
        var idArticle = $(this).val();

        $.ajax({
            type: "POST",
            url: '@Url.Action("_Details", "Article")',
            data: { id: idArticle },
            dataType: 'html',
            success: function (data) {
               $("#ArtDetail").html(data)
            },
            error: function () {
            }
        });
    });


    function ajaxSubmit() {
        var stock = Number($("#lblStock").text());
        var unidades = Number($("#inputUd").val());

        if (unidades <= stock) {
            $("#_ajaxForm").submit();
        } else {
            $(".spValidation").show();
            setTimeout(function () { $(".spValidation").hide(); }, 1000);
        }


    }

    //function showMessage(data) {

    //    if (!data.success) {
           
    //    } else {
           
    //         console.log("Warning");

    //    }

    //     console.log("Ejecutando showMessage");
    //};

    //function clearInput() {
    //    $(".MyInput").val('');
    //    //$(".lbl").text('');
    //    $(".lbl").remove();
    //}
    


</script>

Dashboard/Views/PedidoC/OrderLines.cshtml
@model IEnumerable<Domain.Models.PedidoC.mOrderLine>


@if (TempData["MessageSucces"] != null)
{
    <script>
        $(".MyInput").val('');
        $(".lbl").text('');
        var peso = '@TempData["Peso"]';
        var importe = '@TempData["Importe"]';
        $("#spPeso").text(peso)
        $("#spImporte").text(importe)
    </script>
}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />


<div class="box box-primary flat">
    <div class="box-header with-border">
        <h3 class="box-title">Detalles pedido</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <table id="example2" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"  width="100%">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Linea)</th>
                    <th>@Html.DisplayNameFor(model => model.Lote)</th>
                    <th>@Html.DisplayNameFor(model => model.sArticulo)</th>
                    <th>@Html.DisplayNameFor(model => model.Cantidad)</th>
                    <th>@Html.DisplayNameFor(model => model.Precio)</th>
                    <th>@Html.DisplayNameFor(model => model.Peso)</th>
                    <th>@Html.DisplayNameFor(model => model.TotalPeso) (Kg.)</th>
                    <th>@Html.DisplayNameFor(model => model.Total)</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.Linea)</td>
                        <td>@Html.DisplayFor(model => item.Lote)</td>
                        <td>@Html.DisplayFor(model => item.sArticulo)</td>
                        <td>@Html.DisplayFor(model => item.Cantidad)</td>
                        <td>@Html.DisplayFor(model => item.Precio) €</td>
                        <td>@Html.DisplayFor(model => item.Peso) gr.</td>
                        <td>@Html.DisplayFor(model => item.TotalPeso) Kg.</td>
                        <td>@Html.DisplayFor(model => item.Total) €</td>
                        <td>
                            @Ajax.ActionLink(" ", "DeleteOrderLine", "PedidoC",
                                             new { idOrder = item.Num_ped, idOrderLine = item.Linea },
                                             new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace ,UpdateTargetId = "Odrlist" },
                                             new { @class = "btn btn-default btn-sm flat glyphicon glyphicon-trash", title = "Eliminar" })
                        </td>

                    </tr>
                }
            </tbody>
        </table>

    </div><!-- /.box-body -->
</div><!-- /.box -->



<!-- page script -->

<script type="text/javascript">
    $(function () {
        $('#example2').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json",
            }
        });
    });
</script>