Dashboard/Controllers/LineaPedidoCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Manage;
using Repository;
using Domain.Models.LineaPedidoC;

namespace Dashboard.Controllers
{
    public class LineaPedidoCController : Controller
    {
        //private gLineaPedidoC gLineaPedidoC;
        //private gProduct gProduct;

        //#region Constructors

        //public LineaPedidoCController()
        //{
        //    gLineaPedidoC = new gLineaPedidoC();
        //    gProduct = new gProduct();
        //}

        //#endregion


        ////[HttpGet]
        //public ActionResult Index(int numPed)
        //{
        //    var orderLines = gLineaPedidoC.getElementsById(numPed);

        //    return PartialView(orderLines);
        //}


        //// GET: LineaPedidoC/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}



        //[HttpGet]
        //public ActionResult Create(int NumPed)
        //{
        //    var model = new mCLineaPedido(NumPed);
            
        //    return View(model);
        //}





        //[HttpPost]
        //public ActionResult Create(Linea_pedido_c lpedido,int Unidades)
        //{
        //    if(lpedido.Cantidad > gProduct.count(lpedido.IdArticulo))
        //    {
        //        ModelState.AddModelError(String.Empty, "No hay unidades suficientes");
        //    }

        //    if (!ModelState.IsValid)
        //    {
        //        var model = new mCLineaPedido(lpedido);
        //        model.Unidades = Unidades;
               
        //        return View(model);
        //    }

        //    lpedido.Linea = gLineaPedidoC.getNumLine(lpedido.Num_ped);
        //    if (!gLineaPedidoC.save(lpedido)) throw new Exception("Error al intentar guardar el pedido");

            
        //    return RedirectToAction("Create", new { numPed = lpedido.Num_ped});

        //}




        //// GET: LineaPedidoC/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}




        //// POST: LineaPedidoC/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}




        //// GET: LineaPedidoC/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}




        //// POST: LineaPedidoC/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}




        //#region Private methods

        //private dynamic getNameArticle()
        //{
        //    gProduct gProduct = new gProduct();

        //    var st = gProduct.getElements().Select(
        //       s => new
        //       {
        //           idArt = s.IdArticulo,
        //           Nombre = s.Nombre + "   " + s.Peso + "gr."

        //       });

        //    return st;
        //}


        //#endregion


    }
}

Dashboard/Controllers/PedidoCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Models.PedidoC;
using Domain.Interfaces;
using Repository;
using AutoMapper;
using Domain.DefaultValues;
using Domain.Tools;

namespace Dashboard.Controllers
{
    public class PedidoCController : Controller
    {
        #region Parametros

        private IGenericRepository<Pedido_c> _gPedidoC;
        private IGenericRepository<Clientes> _gClient;
        private IGenericRepository<FormaPago> _gPaymentType;
        private IGenericRepository<EstadosPedido> _gOrderStatus;
        private IGenericRepository<Almacenes> _gStore;
        private IGenericRepository<Linea_pedido_c> _gOrderLine;

        #endregion


        #region Constructores

        public PedidoCController(IGenericRepository<Pedido_c> gPedidoC,
                                 IGenericRepository<EstadosPedido> gOrderStatus,
                                 IGenericRepository<FormaPago> gPaymentType,
                                 IGenericRepository<Clientes> gClient,
                                 IGenericRepository<Almacenes> gStore,
                                 IGenericRepository<Linea_pedido_c> gOrderLine)
        {
            this._gPedidoC = gPedidoC;
            this._gOrderStatus = gOrderStatus;
            this._gPaymentType = gPaymentType;
            this._gClient = gClient;
            this._gStore = gStore;
            this._gOrderLine = gOrderLine;
        }

        #endregion


        [HttpGet]
        public ActionResult Index()
        {
            var list = _gPedidoC.GetAll().ToList();
            var modelList = Mapper.Map<IEnumerable<Pedido_c>, IEnumerable<mPedidoC>>(list).ToList();

            return View(modelList);
        }



        [HttpGet]
        public ActionResult Create()
        {
            var model = new mPedidoCCreate();
            model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
            model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
            model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");
            
            return View(model);
        }



        [HttpPost]
        public ActionResult Create(Pedido_c element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
                    model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
                    model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
                    model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

                    return View(model);
                }

                _gPedidoC.Add(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el contacto. " + ex);
            }

            return RedirectToAction("Index");

        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();

            var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
            model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
            model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
            model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

            return View(model);
        }





        [HttpPost]
        public ActionResult Edit(Pedido_c element)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var model = Mapper.Map<Pedido_c, mPedidoCCreate>(element);
                    model.FormasPago = new SelectList(_gPaymentType.GetAll().ToList(), "IdPago", "Nombre");
                    model.ClientList = new SelectList(_gClient.GetAll().ToList(), "IdCliente", "Razon_Social");
                    model.Estados = new SelectList(_gOrderStatus.GetAll().ToList(), "idEstados", "Nombre");

                    return View(model);
                }

                _gPedidoC.Edit(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar modificar el contacto." + ex);
            }

            return RedirectToAction("Index");
        }





        public ActionResult DeleteConfirmed(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var model = AutoMapper.Mapper.Map<Pedido_c, mPedidoC>(element);

            return View(model);
        }



        [HttpPost]
        public ActionResult Delete(Pedido_c element)
        {
            try
            {
                _gPedidoC.Delete(element);
                _gPedidoC.Save();
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar eliminar el contacto." + ex);
            }

            return RedirectToAction("Index");
        }



        #region lineas pedido


        public ActionResult OpenOrder(int id)
        {
            var element = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var model = Mapper.Map<Pedido_c, mPedidoC>(element);
            return View(model);
        }

        [HttpGet]
        public ActionResult OrderLineCreate(int id)
        {
            var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
            //ViewBag.idOrder = id;

            var model = new mOderLineCreate();
            model.Num_ped = id;


            var list = store.Almacen_Productos.Select(X =>
              new
              {
                  id = X.Id,
                  Name = X.Lote + " - " + X.Articulos.Nombre 
              }
            );

            model.ArticleList = new SelectList(list, "id", "Name");
            
            return PartialView(model);
        }


        [HttpPost]
        public ActionResult OrderLineCreate(Linea_pedido_c element)
        {
            var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
            var article = store.Almacen_Productos.Where(x => x.Id == element.idArticulo).FirstOrDefault();

            if(article.Stock >= element.Cantidad)
            {
                var order = _gPedidoC.FindBy(x => x.Num_ped == element.Num_ped).FirstOrDefault();
                article.Stock -= element.Cantidad;

                order.Peso += element.Cantidad * article.Articulos.Peso;
                order.Importe += (float) (element.Cantidad * article.Articulos.Precio);

                element.Total = (double)(element.Cantidad * article.Articulos.Precio);

                _gOrderLine.Add(element);

                _gOrderLine.Save();
                _gPedidoC.Save();
                _gStore.Save();

               
                TempData["MessageSucces"] = "Completado correctamente";
                TempData["Importe"] = order.Importe.ToString();
                TempData["Peso"] = (order.Peso/1000).ToString();

                var updateOrder = _gPedidoC.FindBy(x => x.Num_ped == element.Num_ped).FirstOrDefault();
                var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(updateOrder.Linea_pedido_c.ToList()).ToList();
                if (Request.IsAjaxRequest()) return PartialView("OrderLines", modelList);

            }else
            {
                TempData["MessageWarning"] = "No hay unidades suficientes";
            }

            return RedirectToAction("OpenOrder", new { id = element.Num_ped });
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult OrderLines(int id)
        {
            var order = _gPedidoC.FindBy(x => x.Num_ped == id).FirstOrDefault();
            var list = order.Linea_pedido_c.ToList();

            var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(list).ToList();
          
            return PartialView(modelList);
        }


        [HttpPost]
        public ActionResult DeleteOrderLine(int idOrder , int idOrderLine)
        {
            try
            {
                var store = _gStore.FindBy(x => x.Id == DefaultStoreValues.DefaultStore).FirstOrDefault();
                var order = _gPedidoC.FindBy(x => x.Num_ped == idOrder).FirstOrDefault();
                var orderLine = order.Linea_pedido_c.Where(x => x.Linea == idOrderLine).FirstOrDefault();
                var article = store.Almacen_Productos.Where(x => x.Articulo == orderLine.Almacen_Productos.Articulos.IdArticulo).FirstOrDefault();

                order.Importe -= (float)(orderLine.Cantidad * orderLine.Almacen_Productos.Articulos.Precio);
                order.Peso -= (orderLine.Cantidad * orderLine.Almacen_Productos.Articulos.Peso);
                article.Stock += orderLine.Cantidad;
                
                order.Linea_pedido_c.Remove(orderLine);

                _gPedidoC.Save();
                _gStore.Save();

                TempData["MessageSucces"] = "Completado correctamente";
                TempData["Importe"] = order.Importe.ToString();
                TempData["Peso"] = (order.Peso / 1000).ToString();

                var modelList = Mapper.Map<IEnumerable<Linea_pedido_c>, IEnumerable<mOrderLine>>(order.Linea_pedido_c.ToList()).ToList();

                return PartialView("OrderLines",modelList);
            }
            catch (Exception ex)
            {
                throw new Exception("Error al intentar eliminar una linea de pedido. " + ex);
            }

        }

Dashboard/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Manage;
using Repository;

namespace Dashboard.Controllers
{
    public class ProductController : Controller
    {
        //private gProduct gProduct;
        //private gStatus gStatus;
        //private gTypeProduct gTypeProduct;
        //private gIVA gIva;

        //#region Constructors

        //public ProductController()
        //{
        //    gProduct = new gProduct();
        //    gStatus = new gStatus();
        //    gTypeProduct = new gTypeProduct();
        //    gIva = new gIVA();
        //}

        //#endregion


        //[HttpGet]
        //public ActionResult Index()
        //{
        //    var productList = gProduct.getElements();
        //    return View(productList);
        //}



        //// GET: Product/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}



        //[HttpGet]
        //public ActionResult Create()
        //{
        //    //ViewBag.Estado = new SelectList(gStatus.getElements(), "IdEstado", "Nombre");
        //    //ViewBag.IVA = new SelectList(gIva.getElements(), "IdIVA", "Porcentaje");
        //    //ViewBag.Tipo = new SelectList(gTypeProduct.getElements(), "IdTipoProd", "Nombre");

        //    return View();
        //}


        //[HttpPost]
        //public ActionResult Create(Articulos product)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        //ViewBag.Estado = new SelectList(gStatus.getElements(), "IdEstado", "Nombre");
        //        //ViewBag.IVA = new SelectList(gIva.getElements(), "IdIVA", "Porcentaje");
        //        //ViewBag.Tipo = new SelectList(gTypeProduct.getElements(), "IdTipoProd", "Nombre");

        //        return View(product);
        //    }

        //    if (!gProduct.save(product)) throw new Exception("Error al intentar guardar el producto");

        //    return RedirectToAction("Index");
        //}

        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    var product = gProduct.getElementById(id);

        //    //ViewBag.Estado = new SelectList(gStatus.getElements(), "IdEstado", "Nombre");
        //    //ViewBag.IVA = new SelectList(gIva.getElements(), "IdIVA", "Porcentaje");
        //    //ViewBag.Tipo = new SelectList(gTypeProduct.getElements(), "IdTipoProd", "Nombre");

        //    return View(product);
        //}



        //[HttpPost]
        //public ActionResult Edit(Articulos product)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        //ViewBag.Estado = new SelectList(gStatus.getElements(), "IdEstado", "Nombre");
        //        //ViewBag.IVA = new SelectList(gIva.getElements(), "IdIVA", "Porcentaje");
        //        ViewBag.Tipo = new SelectList(gTypeProduct.getElements(), "IdTipoProd", "Nombre");

        //        return View(product);
        //    }

        //    if (!gProduct.edit(product)) throw new Exception("Error al intentar modificar el producto");


        //    return RedirectToAction("Index");

        //}



        //[HttpGet]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    var product = gProduct.getElementById(id);
        //    return View(product);
        //}



        //[HttpPost]
        //public ActionResult Delete(Articulos product)
        //{
        //    if (!gProduct.delete(product.IdArticulo)) throw new Exception("Error al intentar eliminar el producto");

        //    return RedirectToAction("Index");

        //}


        //public ActionResult getUnits(int id)
        //{
        //    var units = gProduct.count(id);

        //    return Json(units, JsonRequestBehavior.AllowGet);
        //}
    }
}

Dashboard/Views/LineaPedidoC/Create.cshtml
@model Domain.Models.LineaPedidoC.mCLineaPedido

<div class="row">
    <div class="col-xs-8">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Info. pedido [cliente]</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                @Html.Action("Details", "PedidoC", new { id = Model.Num_ped })
            </div>

        </div>
    </div>

    <div class="col-xs-4">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Añadir producto </h3>
            </div><!-- /.box-header -->
            <div class="box-body">

                @using (Html.BeginForm("Create", "LineaPedidoC", FormMethod.Post))
                {
                    @Html.HiddenFor(model => model.Num_ped)
                    
                    @*@Html.Hidden("Unidades","")*@

                    <div id="Detalle" class="col-xs-12">
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger alert-dismissable", style = "margin:10px;" })

                        <div class="form-horizontal">

                            <div class="form-group">
                                <small>@Html.LabelFor(model => model.IdArticulo, htmlAttributes: new { @class = "control-label col-md-2" })</small>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.IdArticulo, Model.Articulos, "-- Select --", new { @Class = "form-control input-sm", style = "max-width:100%", id= "dropProduct" })
                                    @Html.ValidationMessageFor(model => model.IdArticulo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <small>@Html.LabelFor(model => model.Unidades, htmlAttributes: new { @class = "control-label col-md-2" })</small>
                                <div class="col-md-10">
                                    @Html.Label(Model.Unidades.ToString(), new { @Class = "control-label", style = "padding:3px 4px 2px 4px;", id = "lbUnits" })
                                    <input name="Unidades" type="hidden" id="InputUnits"/>
                                    @Html.ValidationMessageFor(model => model.Unidades, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <small>@Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })</small>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Cantidad, htmlAttributes: new { @class = "form-control input-sm" })
                                    @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                                </div>
                            </div>




                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    @Html.ActionLink("Back to list", "Index", "PedidoC", null, new { @class = "btn btn-default btn-sm" })
                                    <input type="submit" value="Guardar" class="btn  btn-primary btn-sm" />
                                </div>
                            </div>


                            @*<div class="form-group">
                                <input type="submit" value="Guardar" class="btn btn-primary" />
                            </div>*@

                            @*<small>Unidades disponibles</small><br />
                                <div style="background-color:#e6e6e6;">
                                    @Html.Label("Unidades", , new { @Class = "control-label", style = "padding:3px 4px 2px 4px;", id = "lbUnits" })
                                </div>*@
                        </div>


                    </div>



                }
            </div>
        </div>
    </div>

    <div class="col-xs-12">
        @Html.Action("Index", "LineaPedidoC", new { numPed = Model.Num_ped })
    </div>

</div>


<script type="text/javascript">

    var sizeDivInfo = $("#InfoPed").height();
    var sizeDivDetalle = $("#Detalle").height();

    //alert(sizeDivInfo + " " + sizeDivDetalle)

    if (sizeDivInfo > sizeDivDetalle) {
        $("#Detalle").css({ "height": sizeDivInfo });
    }

    if (sizeDivDetalle > sizeDivInfo) {
        $("#InfoPed").css({ "height": sizeDivDetalle });
    }



    $("#dropProduct").change(function () {
        var dato = $("#dropProduct").val();

        $.ajax({
            type: "POST",
            url: '@Url.Action("getUnits", "Product")',
            data: { id: dato },
            dataType: 'json',
            success: function (data) {
                $("#lbUnits").text(data);
                $("#InputUnits").val(data);
                //$("#Unidades").val(data);
            },
            error: function () {
                $("#lbUnits").text("No hay unidades");
            }
        });


    });

    //$(".customForm").each(function () {

    //    var sizeDivInfo = $(this).children(".col-md-10").height();
    //    var sizeDivDetalle = $(this).children(".col-md-2").height();


    //    if (sizeDiv2 > sizeDiv10) {
    //        if (sizeDiv10 < 200) {
    //            $(this).children(".col-md-2").css({ "height": 300, "overflow-x": "hidden", "overflow-y": "scroll" });
    //        } else {
    //            $(this).children(".col-md-2").css({ "height": sizeDiv10, "overflow-x": "hidden", "overflow-y": "scroll" });
    //        }

    //    }

    //    //alert("Tamaño del div(10): " + result + "/r Tamaño del div(2) : " + sizeDiv);
    //});


    //function SendDataList() {
    //    $("#BrowseForm").submit();
    //}

</script>