Dashboard/Controllers/LoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dashboard.ModelBinding;
using Domain.Models.Lote;

namespace Dashboard.Controllers
{
    public class LoteController : Controller
    {
        // GET: Lote
        public ActionResult Index()
        {
            return View();
        }

        // GET: Lote/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Lote/Create
        public ActionResult Create()
        {
            var list = new List<Person>();
            return View(list);
        }

        // POST: Lote/Create
        [HttpPost]
        public ActionResult Create(List<Person> persons )
        {
            try
            {
                //var a = listOfPersons;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Lote/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Lote/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Lote/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Lote/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Dashboard/Views/Lote/Create.cshtml
@model IEnumerable<Domain.Models.Lote.Person>



<div class="row">
    <div class="col-md-12">

        <button onclick="NewLine()" type="button">Nueva linea</button>

        @using (Html.BeginForm("Create", "Lote", FormMethod.Post))
        {
            <button class="btn btn-default pull-right" type="submit">Nueva linea</button>

            <table class="table" id="TablaPrueba">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Dirección</th>
                    </tr>
                </thead>

                <tbody>
              
               
                </tbody>

            </table>
        }
    </div>
</div>


<script type="text/javascript">

    function NewLine() {

        var id = getIndex();
        if (id == null) {
            id = 0;
        } else {
            id = (Number(id) + 1).toString();
        }


        console.log("Id = " + id);

        $('#TablaPrueba > tbody:last-child').append($(
            '<tr id = "' + id + '">' +
                '<td>' +
            '       <input class = "form-control text-box single-line input-sm" type = "text" Value="" Name = "persons['+id+'].Nombre" />' +
            '   </td>' +
              '<td>' +
            '       <input class = "form-control text-box single-line input-sm" type = "text" Value="" Name = "persons[' + id + '].Apellidos" />' +
            '   </td>' +
             '<td>' +
            '       <input class = "form-control text-box single-line input-sm" type = "text" Value="" Name = "persons[' + id + '].Direccion" />' +
            '   </td>' +
            '</tr>'

            ));
    }


    function getIndex() {
        console.log("Buscamos id");

        var id = $('#TablaPrueba tr:last').attr('id');

        console.log("Mostramos id = " + id);

        return id;
    }

</script>